### ISSUE TITLE
Conceal secrets on the helm chart 

### ISSUE THREAD

**Issue by atropos112** [datreeio/admission-webhook-datree#273]
Hello there,

I am running my cluster using argocd with a git repo as ground source of truth. Naturally I wanted admission webhook datree to be present in that repository.

I couldn't find a way (without editing helm chart) to provide token via secret rather than directly in the values override file. Since the token is confidential I would like to avoid having it out in the open in the git repository.

Is there currently a way of doing this? That is can I provide "secret" that has a token instead of providing it directly in the values override?

**Comment by atropos112** [comment]
I had some more ideas along with this one created an pull request here https://github.com/datreeio/admission-webhook-datree/pull/274

**Comment by myishay** [comment]
Resolved by #274
